FROM openjdk:14-jdk-alpine
RUN addgroup -S indicis && adduser -S indicis -G indicis
USER indicis:indicis
ARG JAR_FILE=target/indicis-api-0.0.1-SNAPSHOT.jar 
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]
